apiVersion: apps/v1
kind: Deployment
metadata:
  name: tests3
  labels:
    app: tests3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tests3
  template:
    metadata:
      labels:
        app: tests3
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}

      containers:
        - name: tests3
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "test"
            - name: AWS_SECRET_ACCESS_KEY
              value: "testsecret"
            - name: APP_S3_FILE_TO_UPLOAD
              value: "pom.xml"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
